version: "3"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: php_service
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - seyd-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - .devcontainer/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - seyd-network

  #MySQL Service
  seyd_mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: seyd_db
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql/
      - .devcontainer/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - seyd-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - seyd_mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: seyd_mysql
      MYSQL_ROOT_PASSWORD: "secret"
    networks:
      - seyd-network

  # Redis Service
  seyd_app_redis:
   image: redis:4.0
   container_name: redis
   ports:
     - "6382:6379"
   networks:
     - seyd-network

#Docker Networks
networks:
  seyd-network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
